# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations
INTEGRATION_NAME = "McAfeeMvisionEDR"
DISMISS_THREAT_SCRIPT_NAME = f"{INTEGRATION_NAME} - Dismiss Threat"

TASK_IN_PROGRESS = "IN_PROGRESS"
TASK_COMPLETED = "COMPLETED"
TASK_FAILED = "ERROR"

PAGE_LIMIT = 100
SUMMARY_TO_GET_THREAT_ID = "Case generated by Threat"

# CONNECTORS
CONNECTOR_NAME = "McAfee Mvision EDR - Threats Connector"
DEFAULT_TIME_FRAME = 0
DEFAULT_SEVERITY = "Medium"
ACCEPTABLE_TIME_INTERVAL_IN_MINUTES = 5  # 5min
THREAT_ID_FIELD = "threat_id"
WHITELIST_FILTER = "whitelist"
BLACKLIST_FILTER = "blacklist"
STORED_IDS_LIMIT = 3000

# MANAGERS
DEFAULT_SKIP = 0
PID_PROCESS = "PID"
SHA256_PROCESS = "SHA256"
NAME_PROCESS = "Name"
PATH_PROCESS = "Full Path"

# ACTIONS
PROVIDER_NAME = "McAfeeMvisionEDR"
COMPLETED_STATUS = "COMPLETED"
ERROR_STATUS = "ERROR"
COMPLETED_ERROR_STATUS = "COMPLETED_ERRORS"
IN_PROGRESS_STATUS = "IN_PROGRESS"

GET_TOKEN_ENDPOINT = "https://iam.mcafee-cloud.com/iam/v1.0/token"
