name: Test TIPCommon Package
permissions:
  contents: read
on:
  push:
    branches:
      - '**'
    paths:
      - 'packages/tipcommon/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/tipcommon/**'
      - '.github/workflows/**'

jobs:
  test_tipcommon:
    name: Test TIPCommon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install uv package
        # language=bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Run pytest
        working-directory: packages/tipcommon/TIPCommon
        # language=bash
        run: |
          uv sync --dev
          uv run pytest
